name: nightly-netlify-build

on:
  schedule:
    - cron: "* */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: trigger netlify build
        run: |
          curl -X POST -d '{}' ${{ secrets.NETLIFY_DEPLOY_HOOK }}
